name:                jingle
version:             0.1.0.0
github:              awpr/jingle
license:             BSD3
author:              Andrew Pritchard <awpritchard@gmail.com>
maintainer:          Andrew Pritchard <awpritchard@gmail.com>
copyright:           2022 Andrew Pritchard

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/awpr/jingle#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- portray-prettyprinter
- portray
- wrapped
- megaparsec
- text
- vector
- midi
- lens
- event-list
- non-negative

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jingle:
    source-dirs: app
    main: Main.hs
    dependencies:
      - jingle
      - directory
      - optparse-applicative
      - bytestring
      - process
