resolver: lts-19.23

packages:
- .

extra-deps:
  - git: https://github.com/awpr/portray.git
    commit: e0f68eede0896bdc9fc8998a1eb7678734c8dec9
    subdirs:
      - portray
      - portray-diff
      - portray-prettyprinter
  - wrapped-0.1.0.1
